// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_usageCPU;
lv_obj_t * ui_tempCPU;
lv_obj_t * ui_wCPU;
lv_obj_t * ui_tempGPU;
lv_obj_t * ui_tempGPUH;
lv_obj_t * ui_usageGPU;
lv_obj_t * ui_wGPU;
lv_obj_t * ui_mhzCPU;
lv_obj_t * ui_vCPU;
lv_obj_t * ui_mhzGPU;
lv_obj_t * ui_mbUsageGPU;
lv_obj_t * ui_mUsageGPU;
lv_obj_t * ui_memoryUsage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_480x[1] = {&ui_img_480x320_png};
const lv_img_dsc_t * ui_imgset_gemini_generated_image_zfczfcz[1] = {&ui_img_gemini_generated_image_z590fcz590fcz590_png};
const lv_img_dsc_t * ui_imgset_screen[1] = {&ui_img_screen1_png};
const lv_img_dsc_t * ui_imgset_89376408[1] = {&ui_img_995331464};
const lv_img_dsc_t * ui_imgset_480x320_[1] = {&ui_img_480x320_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
