// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_usageCPU;
extern lv_obj_t * ui_tempCPU;
extern lv_obj_t * ui_wCPU;
extern lv_obj_t * ui_tempGPU;
extern lv_obj_t * ui_tempGPUH;
extern lv_obj_t * ui_usageGPU;
extern lv_obj_t * ui_wGPU;
extern lv_obj_t * ui_mhzCPU;
extern lv_obj_t * ui_vCPU;
extern lv_obj_t * ui_mhzGPU;
extern lv_obj_t * ui_mbUsageGPU;
extern lv_obj_t * ui_mUsageGPU;
extern lv_obj_t * ui_memoryUsage;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_480x320_1_png);    // assets/480x320_1.png
LV_IMG_DECLARE(ui_img_480x320_png);    // assets/480x320.png
LV_IMG_DECLARE(
    ui_img_gemini_generated_image_z590fcz590fcz590_png);    // assets/Gemini_Generated_Image_z590fcz590fcz590.png
LV_IMG_DECLARE(ui_img_screen1_png);    // assets/screen1.png
LV_IMG_DECLARE(ui_img_995331464);    // assets/p1-480x320.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
