// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_480x320_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usageCPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_usageCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usageCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usageCPU, -89);
    lv_obj_set_y(ui_usageCPU, -90);
    lv_obj_set_align(ui_usageCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_usageCPU, "100%");
    lv_obj_set_style_text_font(ui_usageCPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempCPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempCPU, -179);
    lv_obj_set_y(ui_tempCPU, -89);
    lv_obj_set_align(ui_tempCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempCPU, "99,0°C");
    lv_obj_set_style_text_font(ui_tempCPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wCPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wCPU, -133);
    lv_obj_set_y(ui_wCPU, -59);
    lv_obj_set_align(ui_wCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wCPU, "50,5 W");
    lv_obj_set_style_text_font(ui_wCPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempGPU, 28);
    lv_obj_set_y(ui_tempGPU, -88);
    lv_obj_set_align(ui_tempGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempGPU, "99,3°C");
    lv_obj_set_style_text_font(ui_tempGPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempGPUH = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempGPUH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempGPUH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempGPUH, 115);
    lv_obj_set_y(ui_tempGPUH, -88);
    lv_obj_set_align(ui_tempGPUH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempGPUH, "99,5°C");
    lv_obj_set_style_text_font(ui_tempGPUH, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usageGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_usageGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usageGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usageGPU, 196);
    lv_obj_set_y(ui_usageGPU, -89);
    lv_obj_set_align(ui_usageGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_usageGPU, "100%");
    lv_obj_set_style_text_font(ui_usageGPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wGPU, 104);
    lv_obj_set_y(ui_wGPU, -57);
    lv_obj_set_align(ui_wGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wGPU, "120,3 W");
    lv_obj_set_style_text_font(ui_wGPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mhzCPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mhzCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mhzCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mhzCPU, -134);
    lv_obj_set_y(ui_mhzCPU, -26);
    lv_obj_set_align(ui_mhzCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mhzCPU, "4504,0 MHz");
    lv_obj_set_style_text_font(ui_mhzCPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vCPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_vCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vCPU, -134);
    lv_obj_set_y(ui_vCPU, 6);
    lv_obj_set_align(ui_vCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vCPU, "1,294 V");
    lv_obj_set_style_text_font(ui_vCPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mhzGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mhzGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mhzGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mhzGPU, 106);
    lv_obj_set_y(ui_mhzGPU, -26);
    lv_obj_set_align(ui_mhzGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mhzGPU, "1200,0 MHz");
    lv_obj_set_style_text_font(ui_mhzGPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mbUsageGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mbUsageGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mbUsageGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mbUsageGPU, 107);
    lv_obj_set_y(ui_mbUsageGPU, 39);
    lv_obj_set_align(ui_mbUsageGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mbUsageGPU, "3920 MB / 4094 MB");
    lv_obj_set_style_text_font(ui_mbUsageGPU, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mUsageGPU = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mUsageGPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mUsageGPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mUsageGPU, 105);
    lv_obj_set_y(ui_mUsageGPU, 8);
    lv_obj_set_align(ui_mUsageGPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mUsageGPU, "93%");
    lv_obj_set_style_text_font(ui_mUsageGPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memoryUsage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_memoryUsage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_memoryUsage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_memoryUsage, -129);
    lv_obj_set_y(ui_memoryUsage, 39);
    lv_obj_set_align(ui_memoryUsage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_memoryUsage, "11,0 GB/28 GB");
    lv_obj_set_style_text_font(ui_memoryUsage, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);


}
